### PR TITLE
Add separate changelog for unit-splitter-core

### PR DESCRIPTION
**Pull request by Geemili**
Right now I have the changelog in the web crate, and I wanted to record some changes to the core. I'm not sure if I should be keeping two separate changelogs, or if I should just move the web changelog up a directory.

I guess the real choice is if I consider the `cli` and `web` crates separate applications or just separate frontends.

Anyway, I'll decide soon, I guess. :man_shrugging:

### CODE REVIEW

**Comment by desttinghim** [comment]
I think moving the change-log up a directory and then putting the different parts under separate headings would be the best course of action. No need to make people look all over the place for changes, especially since this project isn't very big at the moment.

**Comment by Geemili** [comment]
Yeah, I think I'll do that. Thanks for the feedback!

**Comment by desttinghim** [comment]
You are welcome

**Comment by Geemili** [comment]
Made the change in a separate commit: 39eec14e241d3ef37e35bd88b81cc828ef52dbb5

I didn't want to have a commit adding a file, and then immediately removing.

**Pull request closed without merging**
